import MarkdownIt from 'markdown-it';

/**
 * Additional rendering behavior for shared markdown output.
 */
export interface RenderMarkdownOptions {
  /**
   * Adds `target="_blank"` and `rel="noopener noreferrer"` to `http`, `https`,
   * and protocol-relative links.
   */
  readonly openExternalLinksInNewTab?: boolean;
}

const isExternalLinkHref = (href: string): boolean => /^(?:https?:|\/\/)/iu.test(href);

const createMarkdownRenderer = (openExternalLinksInNewTab = false) => {
  const markdown = new MarkdownIt({
    html: false,
    linkify: false,
    typographer: true,
    breaks: false,
  });

  const fallbackLinkOpenRenderer: NonNullable<typeof markdown.renderer.rules.link_open> = (
    tokens,
    idx,
    options,
    _env,
    self,
  ) => self.renderToken(tokens, idx, options);
  const fallbackTableOpenRenderer: NonNullable<typeof markdown.renderer.rules.table_open> = (
    tokens,
    idx,
    options,
    _env,
    self,
  ) => self.renderToken(tokens, idx, options);
  const fallbackTableCloseRenderer: NonNullable<typeof markdown.renderer.rules.table_close> = (
    tokens,
    idx,
    options,
    _env,
    self,
  ) => self.renderToken(tokens, idx, options);

  const defaultLinkOpenRenderer = markdown.renderer.rules.link_open ?? fallbackLinkOpenRenderer;
  const defaultTableOpenRenderer = markdown.renderer.rules.table_open ?? fallbackTableOpenRenderer;
  const defaultTableCloseRenderer =
    markdown.renderer.rules.table_close ?? fallbackTableCloseRenderer;

  markdown.renderer.rules.table_open = (tokens, idx, options, env, self) =>
    `<div class="markdown-content__table-scroll">${defaultTableOpenRenderer(
      tokens,
      idx,
      options,
      env,
      self,
    )}`;

  markdown.renderer.rules.table_close = (tokens, idx, options, env, self) =>
    `${defaultTableCloseRenderer(tokens, idx, options, env, self)}</div>`;

  if (!openExternalLinksInNewTab) {
    return markdown;
  }

  markdown.renderer.rules.link_open = (tokens, idx, options, env, self) => {
    const token = tokens[idx];

    if (token === undefined) {
      return defaultLinkOpenRenderer(tokens, idx, options, env, self);
    }

    const href = token.attrGet('href');

    if (href !== null && isExternalLinkHref(href)) {
      token.attrSet('target', '_blank');
      token.attrSet('rel', 'noopener noreferrer');
    }

    return defaultLinkOpenRenderer(tokens, idx, options, env, self);
  };

  return markdown;
};

const markdown = createMarkdownRenderer();
const markdownWithExternalLinks = createMarkdownRenderer(true);

/**
 * Renders a repository-controlled Markdown string to safe HTML.
 * @param source - Markdown source string from a repository-controlled input.
 * @param options - Optional rendering behavior flags.
 * @returns Safe HTML generated by the shared markdown-it renderer.
 */
export const renderMarkdown = (source: string, options: RenderMarkdownOptions = {}): string => {
  const renderer = options.openExternalLinksInNewTab ? markdownWithExternalLinks : markdown;

  return renderer.render(source);
};
