import MarkdownIt from 'markdown-it';

/**
 * Additional rendering behavior for shared markdown output.
 */
export interface RenderMarkdownOptions {
  /**
   * Adds `target="_blank"` and `rel="noopener noreferrer"` to `http`, `https`,
   * and protocol-relative links.
   */
  readonly openExternalLinksInNewTab?: boolean;
  /**
   * Optional class name applied to a div that wraps rendered tables.
   */
  readonly tableWrapperClassName?: string;
}

const isExternalLinkHref = (href: string): boolean => /^(?:https?:|\/\/)/iu.test(href);
const allowedAbsoluteLinkProtocolRe = /^(?:https?:|mailto:|tel:)/iu;
const customSchemeRe = /^[a-z][a-z\d+.-]*:/iu;

const isAllowedMarkdownLink = (url: string): boolean => {
  const trimmedUrl = url.trim();

  if (trimmedUrl === '') {
    return false;
  }

  if (allowedAbsoluteLinkProtocolRe.test(trimmedUrl)) {
    return true;
  }

  if (trimmedUrl.startsWith('//')) {
    return true;
  }

  if (
    trimmedUrl.startsWith('/') ||
    trimmedUrl.startsWith('#') ||
    trimmedUrl.startsWith('./') ||
    trimmedUrl.startsWith('../')
  ) {
    return true;
  }

  if (customSchemeRe.test(trimmedUrl)) {
    return false;
  }

  return true;
};

const createMarkdownRenderer = (renderOptions: RenderMarkdownOptions = {}) => {
  const markdown = new MarkdownIt({
    html: false,
    linkify: false,
    typographer: false,
    breaks: false,
  });
  const defaultValidateLink = markdown.validateLink.bind(markdown);
  markdown.validateLink = (url) => defaultValidateLink(url) && isAllowedMarkdownLink(url);
  const { openExternalLinksInNewTab = false, tableWrapperClassName } = renderOptions;

  const fallbackLinkOpenRenderer: NonNullable<typeof markdown.renderer.rules.link_open> = (
    tokens,
    idx,
    rendererOptions,
    _env,
    self,
  ) => self.renderToken(tokens, idx, rendererOptions);
  const fallbackTableOpenRenderer: NonNullable<typeof markdown.renderer.rules.table_open> = (
    tokens,
    idx,
    rendererOptions,
    _env,
    self,
  ) => self.renderToken(tokens, idx, rendererOptions);
  const fallbackTableCloseRenderer: NonNullable<typeof markdown.renderer.rules.table_close> = (
    tokens,
    idx,
    rendererOptions,
    _env,
    self,
  ) => self.renderToken(tokens, idx, rendererOptions);

  const defaultLinkOpenRenderer = markdown.renderer.rules.link_open ?? fallbackLinkOpenRenderer;
  if (tableWrapperClassName !== undefined) {
    const defaultTableOpenRenderer =
      markdown.renderer.rules.table_open ?? fallbackTableOpenRenderer;
    const defaultTableCloseRenderer =
      markdown.renderer.rules.table_close ?? fallbackTableCloseRenderer;
    const escapedTableWrapperClassName = markdown.utils.escapeHtml(tableWrapperClassName);

    markdown.renderer.rules.table_open = (tokens, idx, rendererOptions, env, self) =>
      `<div class="${escapedTableWrapperClassName}">${defaultTableOpenRenderer(
        tokens,
        idx,
        rendererOptions,
        env,
        self,
      )}`;

    markdown.renderer.rules.table_close = (tokens, idx, rendererOptions, env, self) =>
      `${defaultTableCloseRenderer(tokens, idx, rendererOptions, env, self)}</div>`;
  }

  if (!openExternalLinksInNewTab) {
    return markdown;
  }

  markdown.renderer.rules.link_open = (tokens, idx, rendererOptions, env, self) => {
    const token = tokens[idx];

    if (token === undefined) {
      return defaultLinkOpenRenderer(tokens, idx, rendererOptions, env, self);
    }

    const href = token.attrGet('href');

    if (href !== null && isExternalLinkHref(href)) {
      token.attrSet('target', '_blank');
      token.attrSet('rel', 'noopener noreferrer');
    }

    return defaultLinkOpenRenderer(tokens, idx, rendererOptions, env, self);
  };

  return markdown;
};

/**
 * Renders a repository-controlled Markdown string to safe HTML.
 * @param source - Markdown source string from a repository-controlled input.
 * @param options - Optional rendering behavior flags.
 * @returns Safe HTML generated by the shared markdown-it renderer.
 */
export const renderMarkdown = (source: string, options: RenderMarkdownOptions = {}): string => {
  const renderer = createMarkdownRenderer(options);

  return renderer.render(source);
};
