const SESSION_USER_ID_PREFIX = 'session:';

/** Matches exactly `session:<lowercase-uuid>` — the format generated by `getOrCreateSentrySessionId`. */
const SESSION_ID_PATTERN = /^session:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

let sessionId: string | undefined;

/**
 * Returns the session-scoped Sentry user ID, creating it on first call.
 * Stored in memory only — resets on page reload. Never persisted to storage.
 * The format is `session:<uuid>` so `beforeSend` can verify the origin.
 * @returns The session user ID string.
 */
export const getOrCreateSentrySessionId = (): string => {
  sessionId ??= `${SESSION_USER_ID_PREFIX}${crypto.randomUUID()}`;
  return sessionId;
};

/**
 * Returns whether a Sentry user ID is a valid in-memory session-scoped ID.
 * Rejects plain user IDs, emails, account IDs, installation IDs, and any
 * `session:` string that is not followed by a lowercase UUID.
 * @param userId - The value to validate.
 * @returns `true` only when the value matches `session:<uuid>`.
 */
export const isSessionSentryUserId = (userId: unknown): userId is string =>
  typeof userId === 'string' && SESSION_ID_PATTERN.test(userId);
