/**
 * Tracks whether Sentry event delivery is allowed.
 * `unknown` = local settings not yet hydrated.
 * `enabled` = user opted in.
 * `disabled` = user opted out or Sentry unconfigured.
 */
export type SentryReportingState = 'unknown' | 'enabled' | 'disabled';

/**
 * Dynamic runtime state synced from main thread to worker.
 * Only this dynamic state is passed; static config is imported directly.
 */
export type SentryRuntimeState = {
  /** Session-scoped user ID generated by the main thread. */
  sessionId: string;
  /** Current reporting state derived from diagnostics opt-in. */
  reportingState: SentryReportingState;
};
