/**
 * Publish a production build to the root of the gh-pages staging branch.
 *
 * Publishes a new immutable managed release (see the managed pinned
 * application updates feature: `docs/release.md`) into the root's retained
 * `updates/` and `assets/` archive, then applies the stable channel's
 * ordinary deployment files on top. Existing branch and PR preview
 * directories are preserved so stable publishes never evict active
 * non-stable deployments. The shared root `404.html` SPA fallback is also
 * regenerated by the publish filesystem layer.
 *
 * When --output-dir is provided, the final staging content is also copied
 * there so the caller can upload it as a GitHub Pages artifact.
 *
 * Usage:
 *   node scripts/pages/publishStable.mjs --dist ./dist --app-version 1.2.3 \
 *     --build-id <sha> --build-date <canonical-utc-committer-iso> \
 *     [--output-dir ./pages-staging]
 *
 * Required env:
 *   GITHUB_TOKEN      - token with contents:write on the target Pages repository
 *   PAGES_REPOSITORY  - OWNER/REPO of the target Pages repository (never GITHUB_REPOSITORY,
 *                        which is the reserved Actions default pointing at the source repository)
 */

import { pathToFileURL } from 'node:url';

import { withGhPagesBranch } from './lib/ghPagesBranch.mjs';
import { publishManagedRelease } from './lib/releasePublish.mjs';

function readFlag(argv, flag) {
  const index = argv.indexOf(flag);
  return index !== -1 ? argv[index + 1] : undefined;
}

/**
 * @param argv Process arguments (process.argv.slice(2)).
 * @param env Process environment.
 */
export async function publishStable(argv = process.argv.slice(2), env = process.env) {
  const distDir = readFlag(argv, '--dist');
  const appVersion = readFlag(argv, '--app-version');
  const buildId = readFlag(argv, '--build-id');
  const buildDate = readFlag(argv, '--build-date');
  if (!distDir || !appVersion || !buildId || !buildDate) {
    throw new Error(
      'Usage: publishStable.mjs --dist <dist-dir> --app-version <version> --build-id <id> --build-date <canonical-utc-committer-iso>',
    );
  }

  const outputDir = readFlag(argv, '--output-dir');

  const { GITHUB_TOKEN, PAGES_REPOSITORY } = env;
  if (!GITHUB_TOKEN) throw new Error('GITHUB_TOKEN is required');
  if (!PAGES_REPOSITORY) throw new Error('PAGES_REPOSITORY is required');

  await withGhPagesBranch({
    token: GITHUB_TOKEN,
    repository: PAGES_REPOSITORY,
    commitMessage: 'chore(pages): deploy stable build',
    outputDir,
    fn(workDir) {
      publishManagedRelease({
        workDir,
        distDir,
        channel: 'stable',
        appVersion,
        buildId,
        buildDate,
      });
    },
  });

  console.log('Stable build published.');
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    await publishStable();
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
